# Generated by Django 4.2.9 on 2025-01-08 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_article_table_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_category', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
