# Generated by Django 4.2.9 on 2025-01-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_category_create_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_user',
            new_name='created_user',
        ),
    ]
