# Generated by Django 4.2.9 on 2025-01-10 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=datetime.datetime(2025, 1, 10, 5, 31, 50, 72121, tzinfo=datetime.timezone.utc), max_length=1024),
            preserve_default=False,
        ),
    ]
